In [3]:
import pandas as pd

In [4]:
import os

In [ ]:
# os.chdir('C:\\Users\\virrginie.broly\\Documents\\4.Training\\Ironhack\\dataV2-labs\\module-1\\Pipelines-Project')

In [ ]:
# use spyder

In [6]:
shark=pd.read_csv('shark.csv', encoding = 'latin1')

In [8]:
#shark.head()

In [9]:
#shark.info()

In [7]:
shark.shape

(5992, 24)

In [12]:
shark_na = shark.isna().sum()
shark_missing = (shark_na[shark_na>0]/shark.shape[0]*100).round(2)
shark_missing

Case Number                0.02
Country                    0.72
Area                       6.72
Location                   8.29
Activity                   8.79
Name                       3.34
Sex                        9.48
Age                       44.75
Injury                     0.47
Fatal (Y/N)                0.33
Time                      53.61
Species                   48.97
Investigator or Source     0.28
pdf                        0.03
href formula               0.05
href                       0.08
Case Number.1              0.03
Case Number.2              0.03
original order             0.03
Unnamed: 22               99.98
Unnamed: 23               99.97
dtype: float64

Delete the columns that have more than 90% of missing values

In [13]:
drop_cols = shark_missing[shark_missing>90].index
drop_cols

Index(['Unnamed: 22', 'Unnamed: 23'], dtype='object')

In [14]:
shark = shark.drop(drop_cols, axis=1)
shark.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,N,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993.0
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,N,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992.0
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,N,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991.0
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,N,NaN,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990.0
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989.0

# Drop the columns not needed

In [15]:
drop_col = ['Case Number', 'Activity', 'Age', 'Time','Species ','Investigator or Source','pdf','href formula', 'href','Case Number.1','Case Number.2', 'original order']
shark = shark.drop(drop_col, axis=1)
shark.head()

,Date,Year,Type,Country,Area,Location,Name,Sex,Injury,Fatal (Y/N)
0,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",male,M,Minor injury to thigh,N
1,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Chucky Luciano,M,Lacerations to hands,N
2,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",male,M,Lacerations to lower leg,N
3,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Rory Angiolella,M,Struck by fin on chest & leg,N
4,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,male,M,No injury: Knocked off board by shark,N

# Cleaning of Injuries

In [20]:
# Replace the NaN values by 'Not reported'
shark.Injury = shark.Injury.fillna('Not reported')

In [21]:
shark.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5993 entries, 0 to 5992
Data columns (total 10 columns):
Date           5993 non-null object
Year           5993 non-null int64
Type           5993 non-null object
Country        5950 non-null object
Area           5590 non-null object
Location       5496 non-null object
Name           5793 non-null object
Sex            5425 non-null object
Injury         5993 non-null object
Fatal (Y/N)    5973 non-null object
dtypes: int64(1), object(9)
memory usage: 468.3+ KB

In [22]:
# Creation of a dictionnary containing all the different words in the Injury column and their frequency
injury_words = [
    x for x in ' '.join(
        shark.Injury.str.lower().tolist()
    ).split() if x.isalpha()
]
injury_set = set(injury_words)
injury_dct = {i:injury_words.count(i) for i in injury_set}

In [ ]:
# it seams you gave up this next part, so delete from final file or comment if you realy want to keep it!!!!

In [15]:
# Order the dictionnary by frequency
import operator
injury_dct=dict(sorted(injury_dct.items(),key=operator.itemgetter(1),reverse=True))
injury_dct

{'to': 1470,
 'bitten': 1373,
 'shark': 1127,
 'no': 852,
 'fatal': 826,
 'leg': 818,
 'right': 808,
 'left': 807,
 'foot': 713,
 'lacerations': 560,
 'provoked': 554,
 'incident': 549,
 'by': 542,
 'injury': 482,
 'lacerated': 440,
 'hand': 394,
 'the': 388,
 'of': 386,
 'arm': 369,
 'thigh': 368,
 'on': 356,
 'severed': 251,
 'calf': 244,
 'laceration': 232,
 'and': 230,
 'ankle': 218,
 'in': 218,
 'his': 215,
 'minor': 208,
 'a': 205,
 'bit': 202,
 'lower': 189,
 'boat': 176,
 'was': 169,
 'puncture': 163,
 'but': 160,
 'wounds': 158,
 'forearm': 148,
 'not': 146,
 'survived': 144,
 'recovered': 139,
 'hooked': 138,
 'knee': 131,
 'from': 130,
 'sharks': 129,
 'board': 125,
 'he': 122,
 'were': 118,
 'severely': 117,
 'injured': 116,
 'body': 112,
 'injuries': 101,
 'legs': 95,
 'surgically': 88,
 'amputated': 87,
 'with': 83,
 'surfboard': 79,
 'at': 77,
 'remains': 76,
 'shoulder': 75,
 'when': 74,
 'death': 73,
 'it': 72,
 'severe': 71,
 'drowning': 70,
 'heel': 69,
 'torso': 69,
 'both': 67,
 'involvement': 67,
 'taken': 67,
 'off': 62,
 'bumped': 60,
 'after': 59,
 'wrist': 58,
 'rammed': 56,
 'have': 55,
 'as': 52,
 'abdomen': 52,
 'into': 51,
 'been': 51,
 'chest': 50,
 'back': 49,
 'details': 48,
 'found': 47,
 'reported': 46,
 'probable': 46,
 'fingers': 45,
 'buttock': 44,
 'bite': 44,
 'later': 44,
 'swim': 44,
 'him': 44,
 'punctures': 43,
 'hip': 42,
 'fin': 42,
 'that': 42,
 'grabbed': 42,
 'scavenging': 41,
 'killed': 41,
 'struck': 41,
 'finger': 41,
 'water': 41,
 'speared': 40,
 'buttocks': 40,
 'head': 38,
 'human': 37,
 'below': 37,
 'removed': 36,
 'small': 36,
 'then': 36,
 'one': 36,
 'elbow': 36,
 'kayak': 36,
 'occupants': 36,
 'hands': 35,
 'died': 35,
 'above': 35,
 'tail': 35,
 'prior': 35,
 'captive': 35,
 'damaged': 34,
 'multiple': 34,
 'abrasions': 33,
 'upper': 33,
 'caught': 32,
 'netted': 32,
 'diver': 32,
 'or': 31,
 'bites': 31,
 'ski': 30,
 'leapt': 30,
 'abraded': 30,
 'days': 30,
 'cuts': 29,
 'may': 29,
 'feet': 28,
 'its': 28,
 'while': 27,
 'wound': 27,
 'two': 27,
 'made': 26,
 'toe': 26,
 'knocked': 26,
 'arms': 26,
 'shin': 26,
 'hit': 26,
 'had': 25,
 'dorsum': 25,
 'people': 25,
 'confirmed': 24,
 'out': 24,
 'face': 24,
 'side': 24,
 'm': 24,
 'holed': 24,
 'her': 24,
 'drowned': 24,
 'other': 23,
 'due': 23,
 'bruised': 23,
 'fish': 23,
 'shot': 23,
 'took': 22,
 'unconfirmed': 22,
 'presumed': 22,
 'crew': 22,
 'broken': 22,
 'some': 21,
 'wetsuit': 21,
 'thought': 21,
 'bodies': 21,
 'torn': 21,
 'men': 21,
 'attack': 20,
 'toes': 20,
 'man': 19,
 'oar': 19,
 'rescued': 19,
 'cut': 19,
 'abrasion': 18,
 'nipped': 18,
 'ashore': 18,
 'threat': 18,
 'neck': 18,
 'for': 17,
 'harpooned': 17,
 'onboard': 17,
 'gut': 17,
 'be': 17,
 'rudder': 17,
 'thighs': 17,
 'large': 17,
 'marks': 17,
 'scavenged': 17,
 'tore': 17,
 'survivors': 17,
 'being': 17,
 'thumb': 17,
 'washed': 17,
 'hull': 16,
 'disappeared': 16,
 'an': 16,
 'they': 16,
 'only': 16,
 'if': 15,
 'artery': 15,
 'several': 15,
 'their': 15,
 'tissue': 15,
 'speargun': 15,
 'lost': 15,
 'pulled': 15,
 'punctured': 14,
 'canoe': 14,
 'hours': 14,
 'attacked': 14,
 'landed': 14,
 'x': 14,
 'sole': 14,
 'motor': 14,
 'tiger': 14,
 'superficial': 14,
 'sea': 13,
 'dinghy': 13,
 'times': 13,
 'stern': 13,
 'towed': 13,
 'teeth': 13,
 'part': 13,
 'recorded': 13,
 'net': 13,
 'tooth': 13,
 'cause': 13,
 'away': 13,
 'overboard': 12,
 'partial': 12,
 'propeller': 12,
 'posterior': 12,
 'sank': 12,
 'post': 12,
 'fell': 12,
 'ripped': 11,
 'fishing': 11,
 'stepped': 11,
 'repeatedly': 11,
 'defense': 11,
 'dragged': 11,
 'lifted': 11,
 'another': 11,
 'bruises': 11,
 'many': 11,
 'suit': 11,
 'all': 11,
 'collided': 11,
 'gashed': 11,
 'spear': 11,
 'femur': 11,
 'big': 10,
 'is': 10,
 'charged': 10,
 'gaffed': 10,
 'gash': 10,
 'seen': 10,
 'deep': 10,
 'femoral': 10,
 'who': 10,
 'known': 10,
 'possibly': 10,
 'said': 10,
 'seized': 10,
 'next': 10,
 'minutes': 10,
 'nearly': 10,
 'mortem': 10,
 'bottom': 9,
 'day': 9,
 'surfer': 9,
 'diving': 9,
 'missing': 9,
 'shallow': 9,
 'tried': 9,
 'before': 9,
 'nudged': 9,
 'became': 9,
 'display': 9,
 'jumped': 9,
 'area': 8,
 'through': 8,
 'hospital': 8,
 'perished': 8,
 'outboard': 8,
 'groin': 8,
 'capsized': 8,
 'occupant': 8,
 'others': 8,
 'line': 8,
 'passengers': 8,
 'toothmarks': 8,
 'piece': 7,
 'up': 7,
 'including': 7,
 'surface': 7,
 'clothing': 7,
 'twice': 7,
 'onto': 7,
 'trying': 7,
 'chunk': 7,
 'scratched': 7,
 'major': 7,
 'raft': 7,
 'possible': 7,
 'suffered': 7,
 'caused': 7,
 'circled': 7,
 'which': 7,
 'air': 7,
 'accident': 7,
 'fins': 7,
 'believed': 7,
 'cm': 7,
 'bow': 7,
 'white': 7,
 'grazed': 7,
 'dented': 7,
 'thrown': 7,
 'during': 7,
 'swimfin': 7,
 'stripped': 6,
 'suggested': 6,
 'hole': 6,
 'badly': 6,
 'female': 6,
 'forensic': 6,
 'flung': 6,
 'leash': 6,
 'afterwards': 6,
 'nose': 6,
 'over': 6,
 'she': 6,
 'involved': 6,
 'anchor': 6,
 'exposed': 6,
 'weeks': 6,
 'evidence': 6,
 'fishermen': 6,
 'snapped': 6,
 'half': 6,
 'boated': 6,
 'beach': 6,
 'anterior': 6,
 'swam': 6,
 'shore': 6,
 'accidentally': 5,
 'this': 5,
 'probably': 5,
 'amputation': 5,
 'abdominal': 5,
 'hauled': 5,
 'tank': 5,
 'earlier': 5,
 'appeared': 5,
 'flesh': 5,
 'each': 5,
 'resulted': 5,
 'swept': 5,
 'three': 5,
 'most': 5,
 'ship': 5,
 'same': 5,
 'smashed': 5,
 'top': 5,
 'little': 5,
 'chased': 5,
 'sustained': 5,
 'chasing': 5,
 'scratches': 5,
 'although': 5,
 'reportedly': 5,
 'just': 5,
 'dive': 5,
 'trapped': 5,
 'ribs': 5,
 'entangled': 5,
 'determined': 5,
 'fragments': 5,
 'kneecap': 5,
 'questionable': 5,
 'five': 5,
 'fragment': 5,
 'saw': 5,
 'did': 5,
 'inner': 5,
 'divers': 4,
 'lateral': 4,
 'helmet': 4,
 'attempting': 4,
 'them': 4,
 'alive': 4,
 'attacking': 4,
 'unknown': 4,
 'trace': 4,
 'surboard': 4,
 'dead': 4,
 'result': 4,
 'tied': 4,
 'rescue': 4,
 'boot': 4,
 'bicep': 4,
 'pinky': 4,
 'down': 4,
 'pushed': 4,
 'scuba': 4,
 'approached': 4,
 'serious': 4,
 'between': 4,
 'picked': 4,
 'broke': 4,
 'fisherman': 4,
 'shredded': 4,
 'forearms': 4,
 'brushed': 4,
 'there': 4,
 'attempted': 4,
 'damage': 4,
 'listed': 4,
 'almost': 4,
 'leaving': 4,
 'inside': 4,
 'surgical': 4,
 'harassed': 4,
 'life': 4,
 'calves': 4,
 'never': 4,
 'incidents': 4,
 'according': 4,
 'drove': 4,
 'aboard': 4,
 'tiny': 4,
 'foream': 4,
 'cheek': 4,
 'paddleboard': 4,
 'plane': 4,
 'extensive': 4,
 'middle': 4,
 'sleeve': 4,
 'followed': 4,
 'following': 4,
 'few': 4,
 'crushed': 4,
 'woman': 4,
 'embedded': 4,
 'index': 4,
 'island': 4,
 'those': 4,
 'gear': 4,
 'deck': 4,
 'teethmarks': 4,
 'fought': 4,
 'rope': 4,
 'slashed': 4,
 'gangrene': 4,
 'prodded': 4,
 'week': 4,
 'survivor': 4,
 'hampered': 3,
 'within': 3,
 'kicked': 3,
 'waist': 3,
 'came': 3,
 'biting': 3,
 'scull': 3,
 'ankles': 3,
 'cracked': 3,
 'consumed': 3,
 'vessel': 3,
 'ear': 3,
 'rocks': 3,
 'navy': 3,
 'skin': 3,
 'hoax': 3,
 'catapulted': 3,
 'mouth': 3,
 'years': 3,
 'metal': 3,
 'apparently': 3,
 'limbs': 3,
 'rear': 3,
 'paddle': 3,
 'skiboat': 3,
 'rafts': 3,
 'around': 3,
 'hips': 3,
 'still': 3,
 'gas': 3,
 'could': 3,
 'breaking': 3,
 'japanese': 3,
 'went': 3,
 'pieces': 3,
 'trunks': 3,
 'overturned': 3,
 'single': 3,
 'catch': 3,
 'indicated': 3,
 'pelvis': 3,
 'loss': 3,
 'keel': 3,
 'avulsion': 3,
 'examination': 3,
 'near': 3,
 'harness': 3,
 'stitches': 3,
 'pontoon': 3,
 'any': 3,
 'contained': 3,
 'recovery': 3,
 'slammed': 3,
 'dorsal': 3,
 'inury': 3,
 'required': 3,
 'lacerating': 3,
 'person': 3,
 'lifting': 3,
 'am': 3,
 'preceded': 3,
 'barracuda': 3,
 'slight': 3,
 'poked': 3,
 'personnel': 3,
 'fractured': 3,
 'copper': 3,
 'gashes': 3,
 'whom': 3,
 'ring': 3,
 'underwater': 3,
 'decapitated': 3,
 'impaled': 3,
 'marine': 3,
 'bone': 3,
 'miles': 3,
 'catapulting': 3,
 'achilles': 3,
 'passenger': 3,
 'used': 3,
 'holding': 3,
 'tendon': 3,
 'mutilated': 3,
 'palm': 3,
 'entire': 3,
 'minus': 3,
 'thursday': 3,
 'numerous': 3,
 'itself': 3,
 'speculation': 3,
 'camera': 3,
 'scratch': 3,
 'treated': 3,
 'hook': 3,
 'partly': 3,
 'turned': 3,
 'freighter': 3,
 'planks': 3,
 'bones': 3,
 'prop': 3,
 'flexed': 3,
 'swimming': 3,
 'removing': 3,
 'bathing': 3,
 'yards': 3,
 'point': 3,
 'nets': 3,
 'john': 3,
 'surf': 3,
 'considered': 3,
 'knocking': 3,
 'blue': 2,
 'belt': 2,
 'blood': 2,
 'victim': 2,
 'depth': 2,
 'guns': 2,
 'massive': 2,
 'parts': 2,
 'behind': 2,
 'searchers': 2,
 'steel': 2,
 'overturn': 2,
 'platform': 2,
 'lashed': 2,
 'seriously': 2,
 'uprovoked': 2,
 'bathers': 2,
 'gunwale': 2,
 'shortly': 2,
 'january': 2,
 'spinal': 2,
 'mouthed': 2,
 'bruise': 2,
 'also': 2,
 'pinning': 2,
 'shaft': 2,
 'likely': 2,
 'reef': 2,
 'unconscious': 2,
 'depicts': 2,
 'coast': 2,
 'authorities': 2,
 'breastplate': 2,
 'arch': 2,
 'taking': 2,
 'sighted': 2,
 'canoes': 2,
 'foul': 2,
 'four': 2,
 'coat': 2,
 'dean': 2,
 'finally': 2,
 'shoe': 2,
 'bump': 2,
 'released': 2,
 'immediately': 2,
 'aircraft': 2,
 'attached': 2,
 'unidentified': 2,
 'shins': 2,
 'buried': 2,
 'irregular': 2,
 'carrying': 2,
 'rock': 2,
 'fended': 2,
 'suspected': 2,
 'forehead': 2,
 'skeg': 2,
 'facial': 2,
 'beaches': 2,
 'holded': 2,
 'dinged': 2,
 'pants': 2,
 'strong': 2,
 'free': 2,
 'oceanic': 2,
 'doubtful': 2,
 'led': 2,
 'flank': 2,
 'crashed': 2,
 'port': 2,
 'helping': 2,
 'beaten': 2,
 'kayaker': 2,
 'bared': 2,
 'engine': 2,
 'coroner': 2,
 'take': 2,
 'outrigger': 2,
 'whose': 2,
 'avulsed': 2,
 'bait': 2,
 'second': 2,
 'parallel': 2,
 'beat': 2,
 'allegedly': 2,
 'spending': 2,
 'grasped': 2,
 'tip': 2,
 'lassoed': 2,
 'jacket': 2,
 'buddy': 2,
 'time': 2,
 'clamped': 2,
 'causing': 2,
 'shoes': 2,
 'fed': 2,
 'inujury': 2,
 'tangled': 2,
 'first': 2,
 'dog': 2,
 'boy': 2,
 'repelled': 2,
 'righ': 2,
 'initally': 2,
 'kg': 2,
 'pregnant': 2,
 'jaw': 2,
 'sepsis': 2,
 'long': 2,
 'buzzed': 2,
 'postmortem': 2,
 'muscles': 2,
 'bar': 2,
 'continually': 2,
 'press': 2,
 'managed': 2,
 'transom': 2,
 'sinking': 2,
 'colliding': 2,
 'pressure': 2,
 'spotted': 2,
 'scraped': 2,
 'splintered': 2,
 'skiff': 2,
 'so': 2,
 'except': 2,
 'missed': 2,
 'circular': 2,
 'severing': 2,
 'crescent': 2,
 'inflicted': 2,
 'merely': 2,
 'tossing': 2,
 'whitetip': 2,
 'eight': 2,
 'angler': 2,
 'float': 2,
 'significant': 2,
 'injuring': 2,
 'portion': 2,
 'custody': 2,
 'sorcerers': 2,
 'uncomfirmed': 2,
 'drag': 2,
 'brought': 2,
 'cockpit': 2,
 'ate': 2,
 'hitting': 2,
 'alf': 2,
 'floating': 2,
 'women': 2,
 'thorax': 2,
 'uninjured': 2,
 'threatened': 2,
 'mast': 2,
 'deaths': 2,
 'breached': 2,
 'corpses': 2,
 'knees': 2,
 'where': 2,
 'aft': 2,
 'under': 2,
 'occurred': 2,
 'scrape': 2,
 'stingray': 2,
 'trolling': 2,
 'hose': 2,
 'jaws': 2,
 'across': 2,
 'fom': 2,
 'apparent': 2,
 'displays': 2,
 'necessitating': 2,
 'adrift': 2,
 'beneath': 2,
 'force': 2,
 'wood': 2,
 'gouged': 2,
 'trawler': 2,
 'shock': 2,
 'installed': 2,
 'case': 2,
 'competition': 2,
 'german': 2,
 'reach': 2,
 'tossed': 2,
 'slightly': 2,
 'about': 2,
 'condition': 2,
 'pulling': 2,
 'more': 2,
 'reached': 2,
 'hanging': 2,
 'late': 2,
 'inconsistent': 2,
 'rip': 2,
 'efforts': 2,
 'corregidor': 1,
 'march': 1,
 'bodyboard': 1,
 'imprints': 1,
 'prod': 1,
 'cord': 1,
 'destroyer': 1,
 'bc': 1,
 'gig': 1,
 'gaff': 1,
 'months': 1,
 'schoeman': 1,
 'shook': 1,
 'javanese': 1,
 'manila': 1,
 'summoned': 1,
 'mamacos': 1,
 'collision': 1,
 'carcass': 1,
 'mexican': 1,
 'demonstrating': 1,
 'ramme': 1,
 'penis': 1,
 'basket': 1,
 'lifejackets': 1,
 'local': 1,
 'searching': 1,
 'gilles': 1,
 'partner': 1,
 'buttons': 1,
 'skegs': 1,
 'step': 1,
 'dory': 1,
 'breast': 1,
 'distance': 1,
 'ho': 1,
 'arrived': 1,
 'short': 1,
 'door': 1,
 'unclear': 1,
 'falling': 1,
 'surfski': 1,
 'similar': 1,
 'byshark': 1,
 'tendons': 1,
 'frighten': 1,
 'gave': 1,
 'planking': 1,
 'great': 1,
 'tai': 1,
 'gerricke': 1,
 'wedged': 1,
 'socks': 1,
 'coogee': 1,
 'flinging': 1,
 'throwing': 1,
 'jeans': 1,
 'showed': 1,
 'pc': 1,
 'hav': 1,
 'attracted': 1,
 'elsewhere': 1,
 'year': 1,
 'stirling': 1,
 'clubbing': 1,
 'retrieval': 1,
 'offshore': 1,
 'pinched': 1,
 'soaked': 1,
 'fanie': 1,
 'carving': 1,
 'regurgitated': 1,
 'starboard': 1,
 'companion': 1,
 'contact': 1,
 'dakar': 1,
 'scalp': 1,
 'downward': 1,
 'kahuka': 1,
 'internet': 1,
 'fatally': 1,
 'search': 1,
 'swordfish': 1,
 'indicating': 1,
 'sanna': 1,
 'cabarrocas': 1,
 'rare': 1,
 'felt': 1,
 'pup': 1,
 'brightly': 1,
 'space': 1,
 'charges': 1,
 'gloved': 1,
 'chine': 1,
 'higgs': 1,
 'deflating': 1,
 'period': 1,
 'ding': 1,
 'commotion': 1,
 'glancing': 1,
 'parker': 1,
 'steering': 1,
 'medical': 1,
 'advocate': 1,
 'armpit': 1,
 'injure': 1,
 'department': 1,
 'canoet': 1,
 'watson': 1,
 'seaplane': 1,
 'british': 1,
 'turtle': 1,
 'boats': 1,
 'thereafter': 1,
 'bag': 1,
 'estimated': 1,
 'levÃªque': 1,
 'races': 1,
 'walked': 1,
 'slaughtered': 1,
 'surfers': 1,
 'straight': 1,
 'encountered': 1,
 'whenever': 1,
 'herodotus': 1,
 'devour': 1,
 'jamming': 1,
 'livewell': 1,
 'circumstances': 1,
 'wade': 1,
 'surfaced': 1,
 'fire': 1,
 'swimmer': 1,
 'cliff': 1,
 'mesh': 1,
 'captain': 1,
 'ulna': 1,
 'needed': 1,
 'siide': 1,
 'lieut': 1,
 'anklel': 1,
 'investigate': 1,
 'stuck': 1,
 'acerated': 1,
 'climbing': 1,
 'hemorrhage': 1,
 'least': 1,
 'recuers': 1,
 'charter': 1,
 'until': 1,
 'sticks': 1,
 'mayor': 1,
 'wrists': 1,
 'blacktip': 1,
 'measure': 1,
 'passes': 1,
 'etc': 1,
 'collecting': 1,
 'capsize': 1,
 'sufboard': 1,
 'aboriginal': 1,
 'stringer': 1,
 'bill': 1,
 'disaster': 1,
 'joint': 1,
 'sailing': 1,
 'tibia': 1,
 'north': 1,
 'aken': 1,
 'landing': 1,
 'd': 1,
 'lacerattions': 1,
 'breaching': 1,
 'glove': 1,
 'meshing': 1,
 'corrigedor': 1,
 'none': 1,
 'knifed': 1,
 'seabed': 1,
 'flotation': 1,
 'bath': 1,
 'spot': 1,
 'genitalia': 1,
 'protective': 1,
 'fracturing': 1,
 'reports': 1,
 'harrassed': 1,
 'grabbing': 1,
 'surviving': 1,
 'holes': 1,
 'watch': 1,
 'shorts': 1,
 'fossa': 1,
 'contributed': 1,
 'mile': 1,
 'stomach': 1,
 'burns': 1,
 'such': 1,
 'buckled': 1,
 'posteior': 1,
 'leverenz': 1,
 'observed': 1,
 'refueling': 1,
 'flipping': 1,
 'otherwise': 1,
 'leopard': 1,
 'stell': 1,
 'sierakowski': 1,
 'clinton': 1,
 'knives': 1,
 'inoperable': 1,
 'gunpoint': 1,
 'deloss': 1,
 'rivet': 1,
 'loincloth': 1,
 'cold': 1,
 'pole': 1,
 'pull': 1,
 'bringing': 1,
 'ice': 1,
 'momentarily': 1,
 'du': 1,
 'rescuers': 1,
 'prevented': 1,
 'decomposed': 1,
 'biten': 1,
 'carried': 1,
 ...}

In [34]:
body_lst = ['arm','bumped', 'eye','eyebrow','belly','leg','breast','thumb','elbow','fist','finger','foot','feet','ankle','buttocks','hair','neck','hand','wrist','hip','chin','knee','head','lip','mouth','nose','nostril','thigh','ear','bottom','bum','back','underarm','forearm','shoulder','forehead','waist','calf','calves','cheek','eyelash','lash','tooth','teeth','toe','tongue']
clean_dct = {'leg':'leg','foot':'foot','hand':'hand','arm':'arm','thigh':'leg','calf':'leg','ankle':'foot','forearm':'arm','knee':'leg','legs':'leg','shoulder':'arm','wrist':'arm','back':'trunk','fingers':'hand','hip':'hip','finger':'hand','buttocks':'buttocks','head':'face','elbow':'arm','hands':'hand','feet':'foot','arms':'arm','toe':'foot','toes':'foot','neck':'face','thumb':'hand','thighs':'leg','teeth':'face','tooth':'face','bottom':'buttocks','nose':'face','kneecap':'leg','forearms':'arm','calves':'clave','cheek':'face','waist':'waist','ankles':'foot','mouth':'face','hips':'hip','ear':'face','forehead':'face','knees':'leg','bump':'buttocks','armpit':'arm','chine':'trunk','chin':'trunk','elbows':'arm','fist':'hand','wrists':'hand','lip':'face','breast':'trunk','thumbs':'hand','eye':'face','anklel':'foot','nostril':'face', 'chest':'trunk'}

In [36]:
#using redgex here would eliminate the next cleaning stage by selecting only \bear\b
for parts in body_lst:
    for i 
    re.findall(r'\b'+parts+'\w*?,)

SyntaxError: EOL while scanning string literal (<ipython-input-36-87b067545a08>, line 3)

In [29]:
# Make a list of the injury dict keys that starts with the key of the body dict in order to extract the body parts from the innjury dict
lst = []
for i in injury_dct :
    for j in body_lst:
        if i.startswith(j):
            lst.append(i)

In [30]:
# From the injury dict, select only the items that are body part
injury_dct_cleaned1 = { j:injury_dct[j] for i in lst for j in injury_dct if i==j}

In [32]:
injury_dct_cleaned1

{'backed': 1,
 'eye': 1,
 'thigh': 368,
 'waist': 3,
 'foot': 713,
 'mouthed': 2,
 'breastplate': 2,
 'eyewitness': 1,
 'legs': 95,
 'toes': 20,
 'fist': 1,
 'wrists': 1,
 'elbows': 1,
 'calves': 4,
 'leg': 818,
 'hand': 394,
 'feet': 28,
 'knees': 2,
 'bump': 2,
 'head': 38,
 'breast': 1,
 'lip': 1,
 'chine': 1,
 'ear': 3,
 'toothmarks': 8,
 'hip': 42,
 'elbow': 36,
 'shoulder': 75,
 'earlier': 5,
 'thighs': 17,
 'nostril': 1,
 'arms': 26,
 'forehead': 2,
 'knee': 131,
 'thumb': 17,
 'finger': 41,
 'chin': 1,
 'neck': 18,
 'back': 49,
 'heading': 1,
 'thumbs': 1,
 'buttocks': 40,
 'lashed': 2,
 'earthquake': 1,
 'tooth': 13,
 'armpit': 1,
 'kneecap': 5,
 'hips': 3,
 'arm': 369,
 'anklel': 1,
 'nose': 6,
 'fingers': 45,
 'toe': 26,
 'teeth': 13,
 'hands': 35,
 'calf': 244,
 'forearms': 4,
 'fingertips': 1,
 'wrist': 58,
 'ankles': 3,
 'mouth': 3,
 'ankle': 218,
 'teethmarks': 4,
 'bumped': 60,
 'forearm': 148,
 'bottom': 9,
 'cheek': 4}

In [19]:
# Remove from the dictionnary the remaining keys that are not body parts
remove_lst = ['earlier','teethmarks', 'mouthed', 'breastplate', 'lashed', 'eyewitness', 'backed', 'earthquake', 'fingertips','heading','bumped']
for i in remove_lst :
    del injury_dct_cleaned1[i]

In [20]:
injury_dct_cleaned1

{'leg': 818,
 'foot': 713,
 'hand': 394,
 'arm': 369,
 'thigh': 368,
 'calf': 244,
 'ankle': 218,
 'forearm': 148,
 'knee': 131,
 'legs': 95,
 'shoulder': 75,
 'wrist': 58,
 'back': 49,
 'fingers': 45,
 'hip': 42,
 'finger': 41,
 'buttocks': 40,
 'head': 38,
 'elbow': 36,
 'hands': 35,
 'feet': 28,
 'toe': 26,
 'arms': 26,
 'toes': 20,
 'neck': 18,
 'thighs': 17,
 'thumb': 17,
 'teeth': 13,
 'tooth': 13,
 'bottom': 9,
 'toothmarks': 8,
 'nose': 6,
 'kneecap': 5,
 'forearms': 4,
 'calves': 4,
 'cheek': 4,
 'waist': 3,
 'ankles': 3,
 'ear': 3,
 'mouth': 3,
 'hips': 3,
 'bump': 2,
 'forehead': 2,
 'knees': 2,
 'breast': 1,
 'chine': 1,
 'armpit': 1,
 'anklel': 1,
 'wrists': 1,
 'thumbs': 1,
 'lip': 1,
 'nostril': 1,
 'elbows': 1,
 'chin': 1,
 'fist': 1,
 'eye': 1}

In [21]:
# Creation of a dictionary that will affect to each key of injury_dct_cleaned1 a new value for uniformization purpose
clean_dct = {'leg':'leg','foot':'foot','hand':'hand','arm':'arm','thigh':'leg','calf':'leg','ankle':'foot','forearm':'arm','knee':'leg','legs':'leg','shoulder':'arm','wrist':'arm','back':'trunk','fingers':'hand','hip':'hip','finger':'hand','buttocks':'buttocks','head':'face','elbow':'arm','hands':'hand','feet':'foot','arms':'arm','toe':'foot','toes':'foot','neck':'face','thumb':'hand','thighs':'leg','teeth':'face','tooth':'face','bottom':'buttocks','nose':'face','kneecap':'leg','forearms':'arm','calves':'clave','cheek':'face','waist':'waist','ankles':'foot','mouth':'face','hips':'hip','ear':'face','forehead':'face','knees':'leg','bump':'buttocks','armpit':'arm','chine':'trunk','chin':'trunk','elbows':'arm','fist':'hand','wrists':'hand','lip':'face','breast':'trunk','thumbs':'hand','eye':'face','anklel':'foot','nostril':'face', 'chest':'trunk'}

In [22]:
# Create a Body_part_injured column with the various categories of body parts defined in the clean dictionary
# Example : ff Injury contains legs, Body_part_unjured must contain leg in accordance with the clean_dct correspondance
shark['Body_part_injured'] =""

for row in shark.index:
    row_lst=[]
    for i in str(shark.iloc[row,8]).split(" ") :
        for j in clean_dct :
            if i ==j :
                row_lst.append(clean_dct[j])
        shark.iloc[row,10]=' '.join(row_lst)
        
shark.head(20)

,Date,Year,Type,Country,Area,Location,Name,Sex,Injury,Fatal (Y/N),Body_part_injured
0,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",male,M,Minor injury to thigh,N,leg
1,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Chucky Luciano,M,Lacerations to hands,N,hand
2,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",male,M,Lacerations to lower leg,N,leg
3,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Rory Angiolella,M,Struck by fin on chest & leg,N,trunk leg
4,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,male,M,No injury: Knocked off board by shark,N,
5,15-Sep-16,2016,Boat,AUSTRALIA,Western Australia,Bunbury,Occupant: Ben Stratton,NaN,Shark rammed boat. No injury to occupant,N,
6,11-Sep-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",male,M,Minor injury to arm,N,arm
7,07-Sep-16,2016,Unprovoked,USA,Hawaii,"Makaha, Oahu",female,F,Severe lacerations to shoulder & forearm,N,arm arm
8,06-Sep-16,2016,Unprovoked,NEW CALEDONIA,North Province,Koumac,David Jewell,M,FATAL,Y,
9,05-Sep-16,2016,Unprovoked,USA,South Carolina,"Kingston Plantation, Myrtle Beach, Horry County",Rylie Williams,F,Lacerations & punctures to lower right leg,N,leg
10,05-Sep-16,2016,Unprovoked,AUSTRALIA,Western Australia,Injidup,Fraser Penman,M,"No inury, board broken in half by shark",N,
11,04-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Austin Moore,M,Foot bitten,N,
12,01-Sep-16,2016,Unprovoked,USA,California,"Refugio State Beach, Santa Barbara County",Tyler McQuillen,M,Two toes broken & lacerated,N,foot
13,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Sam Cumiskey,M,Lacerations to right foot,N,foot
14,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",male,M,Minor injury to ankle,N,foot
15,27-Aug-16,2016,Unprovoked,REUNION,NaN,Boucan Canot,Laurent Chardard,M,"Right arm severed, ankle severely bitten",N,arm foot
16,25-Aug-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",David Cassetty,M,Minor injury to ankle,N,foot
17,07-Aug-16,2016,Unprovoked,BAHAMAS,New Providence Island,Nassau,Johnny Stoch,M,Lacerations to left leg,N,leg
18,06-Aug-16,2016,Unprovoked,USA,Hawaii,Maui,Connor Baxter,M,"No inury, shark & board collided",N,
19,04-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Nolan Tyler,M,Big toe bitten,N,foot

In [23]:
# Remove the duplicate words in the Body_part_injured column (ex arm arm)
shark['Body_part_injured']= shark['Body_part_injured'].str.replace(r'\b(\w+)(\s+\1)+\b', r'\1')

In [24]:
shark.head(20)

,Date,Year,Type,Country,Area,Location,Name,Sex,Injury,Fatal (Y/N),Body_part_injured
0,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",male,M,Minor injury to thigh,N,leg
1,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Chucky Luciano,M,Lacerations to hands,N,hand
2,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",male,M,Lacerations to lower leg,N,leg
3,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Rory Angiolella,M,Struck by fin on chest & leg,N,trunk leg
4,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,male,M,No injury: Knocked off board by shark,N,
5,15-Sep-16,2016,Boat,AUSTRALIA,Western Australia,Bunbury,Occupant: Ben Stratton,NaN,Shark rammed boat. No injury to occupant,N,
6,11-Sep-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",male,M,Minor injury to arm,N,arm
7,07-Sep-16,2016,Unprovoked,USA,Hawaii,"Makaha, Oahu",female,F,Severe lacerations to shoulder & forearm,N,arm
8,06-Sep-16,2016,Unprovoked,NEW CALEDONIA,North Province,Koumac,David Jewell,M,FATAL,Y,
9,05-Sep-16,2016,Unprovoked,USA,South Carolina,"Kingston Plantation, Myrtle Beach, Horry County",Rylie Williams,F,Lacerations & punctures to lower right leg,N,leg
10,05-Sep-16,2016,Unprovoked,AUSTRALIA,Western Australia,Injidup,Fraser Penman,M,"No inury, board broken in half by shark",N,
11,04-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Austin Moore,M,Foot bitten,N,
12,01-Sep-16,2016,Unprovoked,USA,California,"Refugio State Beach, Santa Barbara County",Tyler McQuillen,M,Two toes broken & lacerated,N,foot
13,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Sam Cumiskey,M,Lacerations to right foot,N,foot
14,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",male,M,Minor injury to ankle,N,foot
15,27-Aug-16,2016,Unprovoked,REUNION,NaN,Boucan Canot,Laurent Chardard,M,"Right arm severed, ankle severely bitten",N,arm foot
16,25-Aug-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",David Cassetty,M,Minor injury to ankle,N,foot
17,07-Aug-16,2016,Unprovoked,BAHAMAS,New Providence Island,Nassau,Johnny Stoch,M,Lacerations to left leg,N,leg
18,06-Aug-16,2016,Unprovoked,USA,Hawaii,Maui,Connor Baxter,M,"No inury, shark & board collided",N,
19,04-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Nolan Tyler,M,Big toe bitten,N,foot

In [25]:
# Add an arm column (boolean: if arm in Body_part_injured the 1 if not 0 )
shark['arm'] =""
for row in shark.index:
    for i in str(shark.iloc[row,10]).split(" ") :
        if i == 'arm':
            shark.iloc[row,11]= 1

In [26]:
# Add the same columns 10 other categories
            
shark['buttocks'] =""
for row in shark.index:
    for i in str(shark.iloc[row,10]).split(" ") :
        if i == 'buttocks':
            shark.iloc[row,12]= 1


shark['clave'] =""
for row in shark.index:
    for i in str(shark.iloc[row,10]).split(" ") :
        if i == 'clave':
            shark.iloc[row,13]= 1

            
shark['face'] =""
for row in shark.index:
    for i in str(shark.iloc[row,10]).split(" ") :
        if i == 'face':
            shark.iloc[row,14]= 1

            
shark['foot'] =""
for row in shark.index:
    for i in str(shark.iloc[row,10]).split(" ") :
        if i == 'foot':
            shark.iloc[row,15]= 1


shark['hand'] =""
for row in shark.index:
    for i in str(shark.iloc[row,10]).split(" ") :
        if i == 'hand':
            shark.iloc[row,16]= 1

            
shark['hip'] =""
for row in shark.index:
    for i in str(shark.iloc[row,10]).split(" ") :
        if i == 'hip':
            shark.iloc[row,17]= 1

            
shark['leg'] =""
for row in shark.index:
    for i in str(shark.iloc[row,10]).split(" ") :
        if i == 'leg':
            shark.iloc[row,18]= 1

            
shark['trunk'] =""
for row in shark.index:
    for i in str(shark.iloc[row,10]).split(" ") :
        if i == 'trunk':
            shark.iloc[row,19]= 1

            
shark['waist'] =""
for row in shark.index:
    for i in str(shark.iloc[row,10]).split(" ") :
        if i == 'waist':
            shark.iloc[row,20]= 1

In [27]:
shark.head()

,Date,Year,Type,Country,Area,Location,Name,Sex,Injury,Fatal (Y/N),...,arm,buttocks,clave,face,foot,hand,hip,leg,trunk,waist
0,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",male,M,Minor injury to thigh,N,...,,,,,,,,1,,
1,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Chucky Luciano,M,Lacerations to hands,N,...,,,,,,1,,,,
2,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",male,M,Lacerations to lower leg,N,...,,,,,,,,1,,
3,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Rory Angiolella,M,Struck by fin on chest & leg,N,...,,,,,,,,1,1,
4,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,male,M,No injury: Knocked off board by shark,N,...,,,,,,,,,,

In [95]:
for i in shark.index:
    for j in ['arm', 'buttocks', 'clave','face','foot','hand','hip','leg','trunk', 'waist'] :
        if shark.loc[i,j]== '':
            shark.loc[i,j]= 0

In [96]:
shark.head()

,Date,Year,Type,Country,Area,Location,Name,Sex,Injury,Fatal (Y/N),...,arm,buttocks,clave,face,foot,hand,hip,leg,trunk,waist
0,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",male,M,Minor injury to thigh,N,...,0,0,0,0,0,0,0,1,0,0
1,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Chucky Luciano,M,Lacerations to hands,N,...,0,0,0,0,0,1,0,0,0,0
2,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",male,M,Lacerations to lower leg,N,...,0,0,0,0,0,0,0,1,0,0
3,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Rory Angiolella,M,Struck by fin on chest & leg,N,...,0,0,0,0,0,0,0,1,1,0
4,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,male,M,No injury: Knocked off board by shark,N,...,0,0,0,0,0,0,0,0,0,0

In [102]:
results = [shark.arm.sum(),shark.buttocks.sum(),shark.clave.sum(),shark.face.sum(),shark.foot.sum(),shark.hand.sum(),shark.hip.sum(),shark.leg.sum(),shark.trunk.sum(),shark.waist.sum()]
injury_results = pd.DataFrame(results, index = ['arm', 'buttocks', 'clave','face','foot','hand','hip','leg','trunk', 'waist'], columns = ['Total'])
injury_results

          Total
arm         514
buttocks     41
clave         3
face         85
foot        703
hand        392
hip          32
leg        1166
trunk        82
waist         3

In [150]:
# Export the results to a csv file
injury_results.to_csv('injury_result.csv', index = True)

# Cleaning of year

For the purpose of our analysis we want to focus on the attacks that took place over the last 5 years (2012-2016)

In [59]:
# Have a look at unique values in Year
shark.Year.unique()

array([2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006,
       2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995,
       1984, 1994, 1993, 1992, 1991, 1990, 1989, 1969, 1988, 1987, 1986,
       1985, 1983, 1982, 1981, 1980, 1979, 1978, 1977, 1976, 1975, 1974,
       1973, 1972, 1971, 1970, 1968, 1967, 1966, 1965, 1964, 1963, 1962,
       1961, 1960, 1959, 1958, 1957, 1956, 1955, 1954, 1953, 1952, 1951,
       1950, 1949, 1948, 1848, 1947, 1946, 1945, 1944, 1943, 1942, 1941,
       1940, 1939, 1938, 1937, 1936, 1935, 1934, 1933, 1932, 1931, 1930,
       1929, 1928, 1927, 1926, 1925, 1924, 1923, 1922, 1921, 1920, 1919,
       1918, 1917, 1916, 1915, 1914, 1913, 1912, 1911, 1910, 1909, 1908,
       1907, 1906, 1905, 1904, 1903, 1902, 1901, 1900, 1899, 1898, 1897,
       1896, 1895, 1894, 1893, 1892, 1891, 1890, 1889, 1888, 1887, 1886,
       1885, 1884, 1883, 1882, 1881, 1880, 1879, 1878, 1877, 1876, 1875,
       1874, 1873, 1872, 1871, 1870, 1869, 1868, 1867, 1866, 1865, 1864,
       1863, 1862, 1861, 1860, 1859, 1858, 1856, 1855, 1854, 1853, 1852,
       1851, 1850, 1849, 1847, 1846, 1845, 1844, 1842, 1841, 1840, 1839,
       1837, 1836, 1835, 1834, 1832, 1831, 1830, 1829, 1828, 1827, 1826,
       1825, 1822, 1819, 1818, 1817, 1816, 1812, 1811, 1807, 1805, 1804,
       1803, 1800, 1791, 1788, 1787, 1785, 1779, 1776, 1771, 1767, 1764,
       1758, 1749, 1755, 1748, 1742, 1738, 1733, 1721, 1703, 1700, 1642,
       1638, 1637, 1617, 1595, 1580, 1555, 1554, 1543,  500,   77,    5,
          0], dtype=int64)

In [60]:
# Count the number of rows per unique value in Year
year_count = shark.Year.value_counts()
year_count

2015    139
2011    128
2014    125
0       124
2013    122
       ...
1742      1
1758      1
1818      1
1822      1
1595      1
Name: Year, Length: 232, dtype: int64

In [63]:
# Have a look at the 124 lines that have year = 0
year_0 = shark[shark['Year'] == 0]

In [64]:
# Have a look at the unique Date of the row that have year = 0
year_0.Date.unique()

array(['Ca. 214 B.C.', 'Ca. 336.B.C..', '493 B.C.', 'Ca. 725 B.C.',
       '1990 or 1991', 'Before 2016', 'Before Oct-2009', 'Before 1934',
       '2009?', 'Before 1930', '1880-1899', 'Before 1909', 'Before 2012',
       'Before 1916', 'Between   1951-1963', 'Before 1908', 'Before 1900',
       'Before 1876', 'Before 2011', 'Before 2009', 'Beforer 1994',
       'Before 1963', '1896-1913', 'Before 1936', 'Before 08-Jun-1912',
       'Before 1911', 'Before 1901', 'No date, late 1960s', 'Before 2006',
       'Before 2003', 'Before 2004', 'Before 1962', '1950s',
       'No date, Before 1963', '2003?', 'No date', 'Before Feb-1998',
       'No date, Before May-1996', 'No date, Before Mar-1995',
       'Before 1996', 'No date, Before Aug-1989',
       'No date, Before Aug-1987', 'No date, Before 1987',
       'No date, Before  1975', 'No date, Before 1975',
       'No date, Before 1969', 'No date, Before 3-Jan-1967',
       'No date, Before 8-May-1965', 'No date, Before 1902',
       'No date, After August 1926 and before 1936', 'Before 1961',
       '1960s', 'Before 1960', 'Before  19-Jun-1959',
       'Before  24 Apr-1959', 'Before  1958', 'Before 1958',
       'Before 1957', 'Before 1956', 'Before Mar-1956', 'Before 1952',
       '1941-1945', '"During the war" 1943-1945', '"Before the war"',
       'Said to be 1941-1945, more likely 1945', '1941-1942',
       '1940 - 1950', '1940-1946', 'Before 1905', 'World War II',
       'A few years before 1938', 'Early 1930s', 'Before 1927',
       'Between 1918 & 1939', '1920 -1923', 'Before 1921', 'Before 1917',
       'Before          17-Jul-1916',
       'No date (3 days after preceding incident) & prior to 19-Jul-1913',
       'Before          19-Jul-1913', 'Circa 1862', 'Before 1906',
       'Before 1903', '1900-1905', '1883-1889', '1845-1853'], dtype=object)

In [65]:
# They are all out of our scope except maybe the 'Before 2016' row so let's have a look at this one
shark[(shark['Year'] == 0) & (shark['Date'] == 'Before 2016')]

,Date,Year,Type,Country,Area,Location,Name,Sex,Injury,Fatal (Y/N),...,arm,buttocks,clave,face,foot,hand,hip,leg,trunk,waist
5873,Before 2016,0,Unprovoked,KENYA,Mombasa,Kilindini,Hamisi Njenga,M,FATAL,Y,...,,,,,,,,,,

After investigating on the internet we did not found any additional information so we will keep the row as it is

# Cleaning of country

Country is needed in order to determine where we will open a new office. But for this purpose we will focus on the last 5 years so we will narrow the scope of our investigation to 2012-2016

In [30]:
shark.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5992 entries, 0 to 5991
Data columns (total 21 columns):
Date                 5992 non-null object
Year                 5992 non-null int64
Type                 5992 non-null object
Country              5949 non-null object
Area                 5590 non-null object
Location             5496 non-null object
Name                 5792 non-null object
Sex                  5425 non-null object
Injury               5992 non-null object
Fatal (Y/N)          5973 non-null object
Body_part_injured    5992 non-null object
arm                  5992 non-null object
buttocks             5992 non-null object
clave                5992 non-null object
face                 5992 non-null object
foot                 5992 non-null object
hand                 5992 non-null object
hip                  5992 non-null object
leg                  5992 non-null object
trunk                5992 non-null object
waist                5992 non-null object
dtypes: int64(1), object(20)
memory usage: 983.2+ KB

In [74]:
# Creation of a dataframe that focus only on the 2012-2016 period
shark_5Y = shark[shark['Year'] >= 2012]
shark_5Y.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 606 entries, 0 to 605
Data columns (total 21 columns):
Date                 606 non-null object
Year                 606 non-null int64
Type                 606 non-null object
Country              605 non-null object
Area                 572 non-null object
Location             571 non-null object
Name                 603 non-null object
Sex                  584 non-null object
Injury               606 non-null object
Fatal (Y/N)          605 non-null object
Body_part_injured    606 non-null object
arm                  606 non-null object
buttocks             606 non-null object
clave                606 non-null object
face                 606 non-null object
foot                 606 non-null object
hand                 606 non-null object
hip                  606 non-null object
leg                  606 non-null object
trunk                606 non-null object
waist                606 non-null object
dtypes: int64(1), object(20)
memory usage: 104.2+ KB

In [75]:
# Let's have a look at the different countries
shark_5Y.Country.value_counts()

USA                        313
AUSTRALIA                  128
SOUTH AFRICA                30
BAHAMAS                     19
REUNION                     12
FRENCH POLYNESIA            10
SPAIN                        9
NEW ZEALAND                  8
NEW CALEDONIA                8
BRAZIL                       7
MEXICO                       5
JAPAN                        4
JAMAICA                      3
MOZAMBIQUE                   3
FIJI                         2
EGYPT                        2
TAIWAN                       2
ITALY                        2
ECUADOR                      2
TRINIDAD & TOBAGO            2
FRANCE                       2
CAYMAN ISLANDS               2
ARUBA                        1
MAURITIUS                    1
CROATIA                      1
SEYCHELLES                   1
DIEGO GARCIA                 1
ATLANTIC OCEAN               1
INDONESIA                    1
TONGA                        1
KIRIBATI                     1
CANADA                       1
BELIZE                       1
NIGERIA                      1
PAPUA NEW GUINEA             1
SAUDI ARABIA                 1
THAILAND                     1
ISRAEL                       1
COLUMBIA                     1
ST. MARTIN                   1
CAPE VERDE                   1
PHILIPPINES                  1
GUAM                         1
CHILE                        1
PUERTO RICO                  1
GREECE                       1
CHINA                        1
UNITED ARAB EMIRATES         1
PALESTINIAN TERRITORIES      1
Fiji                         1
DOMINICAN REPUBLIC           1
SCOTLAND                     1
Name: Country, dtype: int64

In [78]:
# The only problem is Fiji and FIJI so we will upper all the column to avoid the issue
shark.Country = shark.Country.str.upper()

In [79]:
shark[shark['Year'] >= 2012].Country.value_counts()

USA                        313
AUSTRALIA                  128
SOUTH AFRICA                30
BAHAMAS                     19
REUNION                     12
FRENCH POLYNESIA            10
SPAIN                        9
NEW CALEDONIA                8
NEW ZEALAND                  8
BRAZIL                       7
MEXICO                       5
JAPAN                        4
FIJI                         3
JAMAICA                      3
MOZAMBIQUE                   3
TAIWAN                       2
TRINIDAD & TOBAGO            2
CAYMAN ISLANDS               2
EGYPT                        2
FRANCE                       2
ITALY                        2
ECUADOR                      2
CANADA                       1
KIRIBATI                     1
INDONESIA                    1
CROATIA                      1
BELIZE                       1
ARUBA                        1
DIEGO GARCIA                 1
TONGA                        1
ATLANTIC OCEAN               1
MAURITIUS                    1
NIGERIA                      1
SEYCHELLES                   1
PAPUA NEW GUINEA             1
THAILAND                     1
ISRAEL                       1
COLUMBIA                     1
ST. MARTIN                   1
CAPE VERDE                   1
PHILIPPINES                  1
GUAM                         1
CHILE                        1
PUERTO RICO                  1
GREECE                       1
CHINA                        1
UNITED ARAB EMIRATES         1
PALESTINIAN TERRITORIES      1
DOMINICAN REPUBLIC           1
SAUDI ARABIA                 1
SCOTLAND                     1
Name: Country, dtype: int64

In [81]:
# Now let's have a look at the NaN countries for our period scope
shark[(shark['Year'] >= 2012) & (shark['Country'].isna())]

,Date,Year,Type,Country,Area,Location,Name,Sex,Injury,Fatal (Y/N),...,arm,buttocks,clave,face,foot,hand,hip,leg,trunk,waist
303,Aug-14,2014,Invalid,NaN,NaN,NaN,Cuban refugees,M,Shark involvement prior to death not confirmed,Y,...,,,,,,,,,,

In [85]:
# After investigating, we have learned that the incident happened between Cuba and FLorida so we will assign it to the USA
shark.iloc[303,'Country'] = 'USA'

In [87]:
shark[(shark['Year'] >= 2012) & (shark['Country'].isna())]

Empty DataFrame
Columns: [Date, Year, Type, Country, Area, Location, Name, Sex , Injury, Fatal (Y/N), Body_part_injured, arm, buttocks, clave, face, foot, hand, hip, leg, trunk, waist]
Index: []

[0 rows x 21 columns]

In [139]:
# Create a dictionary with the count of accident per country over the last 5 years
unique_countries = shark[shark['Year'] >= 2012].Country.unique()
year_list = [2012, 2013,2014,2015,2016]
year_dct = {j:[shark[(shark['Year'] == i) & (shark['Country']==j)].Country.count() for i in year_list] for j in unique_countries}
year_dct

{'USA': [64, 60, 66, 72, 52],
 'AUSTRALIA': [26, 20, 29, 30, 23],
 'NEW CALEDONIA': [0, 1, 1, 1, 5],
 'REUNION': [3, 3, 1, 4, 1],
 'BAHAMAS': [2, 7, 3, 3, 4],
 'SPAIN': [0, 1, 4, 2, 2],
 'CHINA': [0, 0, 0, 0, 1],
 'JAPAN': [0, 0, 3, 0, 1],
 'COLUMBIA': [0, 0, 0, 0, 1],
 'SOUTH AFRICA': [5, 8, 5, 9, 3],
 'EGYPT': [0, 0, 0, 1, 1],
 'NEW ZEALAND': [2, 2, 3, 0, 1],
 'INDONESIA': [0, 0, 0, 0, 1],
 'FRENCH POLYNESIA': [1, 2, 2, 4, 1],
 'CAPE VERDE': [0, 0, 0, 0, 1],
 'FIJI': [1, 0, 0, 1, 1],
 'BRAZIL': [1, 2, 1, 2, 1],
 'DOMINICAN REPUBLIC': [0, 0, 0, 0, 1],
 'CAYMAN ISLANDS': [0, 0, 1, 0, 1],
 'UNITED ARAB EMIRATES': [0, 0, 0, 0, 1],
 'ARUBA': [0, 0, 0, 1, 0],
 'MOZAMBIQUE': [0, 0, 0, 3, 0],
 'THAILAND': [0, 0, 0, 1, 0],
 'PUERTO RICO': [0, 0, 0, 1, 0],
 'ITALY': [1, 0, 0, 1, 0],
 'MEXICO': [2, 2, 0, 1, 0],
 'ATLANTIC OCEAN': [0, 0, 0, 1, 0],
 'GREECE': [0, 0, 1, 0, 0],
 'MAURITIUS': [0, 0, 1, 0, 0],
 'ST. MARTIN': [0, 0, 1, 0, 0],
 'FRANCE': [0, 1, 1, 0, 0],
 'ECUADOR': [0, 1, 0, 1, 0],
 'PAPUA NEW GUINEA': [0, 0, 1, 0, 0],
 'TRINIDAD & TOBAGO': [1, 0, 1, 0, 0],
 'KIRIBATI': [0, 1, 0, 0, 0],
 'ISRAEL': [0, 1, 0, 0, 0],
 'DIEGO GARCIA': [0, 1, 0, 0, 0],
 'TAIWAN': [1, 1, 0, 0, 0],
 'JAMAICA': [0, 3, 0, 0, 0],
 'PALESTINIAN TERRITORIES': [0, 1, 0, 0, 0],
 'GUAM': [0, 1, 0, 0, 0],
 'SEYCHELLES': [0, 1, 0, 0, 0],
 'BELIZE': [0, 1, 0, 0, 0],
 'PHILIPPINES': [0, 1, 0, 0, 0],
 'NIGERIA': [1, 0, 0, 0, 0],
 'TONGA': [1, 0, 0, 0, 0],
 'SCOTLAND': [1, 0, 0, 0, 0],
 'CANADA': [1, 0, 0, 0, 0],
 'CROATIA': [1, 0, 0, 0, 0],
 'SAUDI ARABIA': [1, 0, 0, 0, 0],
 'CHILE': [1, 0, 0, 0, 0]}

In [148]:
# Create a dataframe with the dictionary created
country_result_df= pd.DataFrame(year_dct).transpose()
country_result_df.columns = year_list

In [149]:
# Export the results to a csv file
country_result_df.to_csv('country_result.csv', index = True)